version: '3.8'

services:
  db:
    image: rapidfort/postgresql:16.0.0
    env_file:
      - .env
    volumes:
      - postgres-data:/bitnami/postgresql
    networks:
      - rosen_network
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB']
      interval: 10s
      timeout: 5s
      retries: 3

  service:
    image: ghcr.io/zargarzadehm/guard-service:${GUARD_IMAGE_VERSION:-latest}
    environment:
      - POSTGRES_HOST=db
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./config/local.yaml
        target: /app/config/local.yml
      - type: bind
        source: ./config/thresholds.json
        target: /app/config/thresholds.json
      - ./logs/guard-logs/:/app/logs/
      - guard-data:/app/peer-dialer/
      - ./logs/tss-api-logs/:/app/tss-api/logs/
      - tss-api-data:/app/tss-api/home/
    networks:
      - rosen_network
    restart: always
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ['CMD-SHELL', 'curl --fail http://$$HOSTNAME:8080/swagger || exit 1']
      interval: 10s
      timeout: 5s
      retries: 3

  ui:
    image: ghcr.io/rosen-bridge/ui-guard:${UI_IMAGE_VERSION:-latest}
    networks:
      - rosen_network
    restart: always
    ports:
      - 127.0.0.1:${GUARD_PORT:-8081}:80
    volumes:
      - nginx-logs:/var/log/nginx
    depends_on:
      service:
        condition: service_healthy

volumes:
  postgres-data:
  guard-data:
  tss-api-data:
  nginx-logs:

networks:
  rosen_network:
